### ISSUE TITLE
Make it easy to discover kit-hato

### ISSUE THREAD

**Issue by vemv** [kit-clj/kit#104]
Hey there,

AFAIK there's no kit-hato module, and https://kit-clj.github.io/docs/kit-hato.html doesn't point to a set of Maven coordinates. I had to find https://clojars.org/io.github.kit-clj/kit-hato independently.

Not a big deal but I figured an issue could help.

Cheers - V

**Comment by gerdint** [comment]
A module would be nice, but failing that I guess this is the reason why the Maven coords are listed quite prominently on the [Kit GitHub frontpage](https://github.com/kit-clj/kit#latest-versions)

**Comment by yogthos** [comment]
I've linked to the version under the useful libraries section here https://kit-clj.github.io/docs/useful_libraries.html

A module for hato would be easy to add, would just need to inject a component and a dependency. If anybody wants to take a look, I'd be happy to take a PR for that. Would just need to add it here https://github.com/kit-clj/modules

**Comment by jmarijano** [comment]
Hi, I saw that this issue had the "good first issue" label on it. I forked the modules repository and wanted to check if I'm on the right track to add the hato module. Link to the diff: [Add hato module](https://github.com/kit-clj/modules/compare/master...jmarijano:modules:master)

**Comment by yogthos** [comment]
Hi, thanks for taking interest and the diff looks about right to me.

**Comment by jmarijano** [comment]
Thanks for looking at it. I will create a pull request.
