### ISSUE TITLE
how to hot reload sql functions

### ISSUE THREAD

**Issue by vinurs** [kit-clj/kit#106]
when develop, i add a new function in the sql file
```
-- :name get-user-by-id :? :1
-- :doc returns a user object by id, or nil if not present
SELECT *
FROM user_profile
WHERE id = :id;
```
then, how can i hot reload the sql file, and exec the function?

**Comment by vinurs** [comment]
everytime when i add a new sql function , i should re-run `(def query-fn (:db.sql/query-fn state/system))`

**Comment by yogthos** [comment]
It would be better to use a `(defn query-fn [] (:db.sql/query-fn state/system))`, this way it'll grab the fresh state of the system when it's called.

**Comment by vinurs** [comment]
Yes, that solves this problem，thanks
