### ISSUE TITLE
The Kit Clojurescript Docs uses an incorrect function to render to the DOM.

### ISSUE THREAD

**Issue by UnchartedSystems** [kit-clj/kit#109]
In the Kit #clojurescript Docs, under the **Reagent** header, this is stated:

> Finally, rendering components is accomplished by calling the render-component function:
> `(defn render-simple []
>   (reagent/render-component [input-field] (.-body js/document))`

![image](https://github.com/kit-clj/kit/assets/20145459/ab2f9d85-1a8e-48fd-876e-c64aeed7c176)

`reagent.core/render-component` does not exist in Reagent 1.1.1 (the version used in the Kit docs), or in Reagent 1.2.0. The function used to render a react component onto the DOM is `reagent.dom/render`. (`reagent.core/render` is depreciated.)

**Comment by yogthos** [comment]
thanks, updated the doc here https://github.com/kit-clj/kit-clj.github.io/blob/master/resources/md/clojurescript.md
