### ISSUE TITLE
New project: "Error building classpath. Could not find artifact io.github.kit-clj:kit-undertow:jar:1.0.6 in central (https://repo1.maven.org/maven2/)"

### ISSUE THREAD

**Issue by natedaiger** [kit-clj/kit#112]
Disclaimer: I'm totally new to Clojure.

Following the guide here: https://kit-clj.github.io/docs/guestbook.html#guestbook_application

I generated a project (adjusting the command to use `clojure -Tclj-new` instead of `clojure -Tnew`) but the dev server failed to start (`clj -M:dev`) with this error:

`Error building classpath. Could not find artifact io.github.kit-clj:kit-undertow:jar:1.0.6 in central (https://repo1.maven.org/maven2/)`

It looks like that just indicates the latest version of kit-undertow hasn't made it to the central maven repo.

Dropping the undertow version in `deps.edn` to `1.0.5` fixed the issue and the dev server starts:

```clojure
io.github.kit-clj/kit-undertow {:mvn/version "1.0.5"}
```

**Comment by muthuishere** [comment]
Yes the above will work , or please add the clojars repository in deps.edn so that it can find from clojars

```
  :mvn/repos {"central" {:url "https://repo1.maven.org/maven2/"}
             "clojars" {:url "https://repo.clojars.org/"}
 
            #_()}

```

It seems its published here https://clojars.org/io.github.kit-clj/kit-undertow , not in maven.

**Comment by yogthos** [comment]
@natedaiger should be resolved now, looks like it didn't get pushed out. @muthuishere Clojars is considered by default with deps, but the library didn't get released initially 😓
