### ISSUE TITLE
creating template with deps-new does not create folders properly in windows

### ISSUE THREAD

**Issue by muthuishere** [kit-clj/kit#113]
I used the below command to create a template.
neil new io.github.kit-clj/kit  deemwar/helloweb

The expectation is to create all source code files under folders deemwar/helloweb

It works fine in mac , But in windows ,folders are not created.
neil , babashka ,clojure installed via scoop in windows

Mac Screen shot
<img width="485" alt="image" src="https://github.com/kit-clj/kit/assets/132564/7731c9d1-5764-4cca-982f-b672f7a1854d">

Windows Screenshot
<img width="545" alt="image" src="https://github.com/kit-clj/kit/assets/132564/a7be18dc-ad3c-450a-a790-b0519cf8e12a">

**Comment by yogthos** [comment]
Unfortunately, I don't have windows to test locally. It sounds like there's a path issue, could be that there's a hardcoded `/` separator somewhere that should be `File/separator` instead.

**Comment by muthuishere** [comment]
It did worked with  clj-new after fixing the powershell quote issue

The below does not work

```
 clojure -Tcljnew create :template io.github.kit-clj :name yourname/apps
```


The below works

``` 
 clojure -Tcljnew create :template io.github.kit-clj :name """yourname/apps"""
```

but for deps-new , I could not know , how to pass these parameters?

**Comment by yogthos** [comment]
Ah I see, I guess the issue is with powershell escaping then?

**Comment by muthuishere** [comment]
Yeah , the issue is resolved in clj-new , now  i need your help , how to fix with deps-new

**Comment by yogthos** [comment]
Unfortunately, I'm not entirely sure what to do there either. Could you try using bash on windows to see if it'll work that way?

**Comment by muthuishere** [comment]
I tried using git bash , But the issue still exists. I have a question , How did neil gets translated to deps-new , 

``` neil new io.github.kit-clj/kit deemwar/helloweb ```

what would be the translated deps-new cli version any idea?

**Comment by yogthos** [comment]
Good question, might be worth opening an issue for neil

**Comment by muthuishere** [comment]
Also clj-new works well ,Only issue is with deps-new ,  can you point me which one is executed for clj-new and which one for deps-new?

**Comment by yogthos** [comment]
Here's the PR for deps-new https://github.com/kit-clj/kit/pull/72

**Comment by muthuishere** [comment]
I could able to fix it , Its  File Seperator issue  as you said initially , I have updated  the tests as well , so it could be platform independent. Can i raise a PR?

**Comment by muthuishere** [comment]
raised a fix  , explained here what changes has been updated https://www.twitch.tv/videos/1919389924

**Comment by yogthos** [comment]
Thanks, and the change looks good.

**Comment by yogthos** [comment]
And just pushed out a template update to Clojars, if everything looks good on your end I think we can close. Thanks again for investigating.

**Comment by muthuishere** [comment]
Thanks a lot , It works now in windows
