### ISSUE TITLE
clj-new alias could cause confusion

### ISSUE THREAD

**Issue by seancorfield** [kit-clj/kit#116]
The `clj-new` documentation suggests installing it as `clj-new`.

The `deps-new` documentation suggests installing it as `new`.

I would appreciate you updating your readme/docs to use `clj-new` as the alias for `clj-new` so it doesn't cause problems or confusion for people using either of those tools separately since their usage won't match what you have in your README.

You might also want to consider suggesting `clojure -Ttools install-latest :lib io.github.seancorfield/clj-new :as clj-new` so they don't have to worry about versions.

**Comment by yogthos** [comment]
Thanks for the heads up, just updated the docs with the suggestions. As a side note, all the docs live here, and PRs are definitely welcome if you see anything you'd like changed https://github.com/kit-clj/kit-clj.github.io/tree/master/resources

**Comment by seancorfield** [comment]
Thanks! I'll have a check through later today -- I was updating clojure-doc.org ecosystem page about Web Development so I added Kit there (Luminus was already there) and that's when I noticed it.

**Comment by yogthos** [comment]
I think that part is fine since it's just used locally for testing when working on the template, and doesn't affect the users. And Kit should work with `deps-new` currently. @rads added support in this PR https://github.com/kit-clj/kit/pull/72

**Comment by seancorfield** [comment]
Oh nice! Thanks. I sure would love to see all the docs change over to `deps-new` and use `:as new` / `-Tnew` at some point 😄 LMK if there's anything I can do to help make that happen.

**Comment by yogthos** [comment]
Oh yeah I'm definitely open to updating the docs to make `deps-new` the default. If you have a few min to try it locally to make sure the project generates as expected, just want to make sure it works outside my local setup before updating. :)
