### ISSUE TITLE
Missing or unclear documentation on profiles, modules and libraries

### ISSUE THREAD

**Issue by markokocic** [kit-clj/kit#12]
By looking at the documentation it's not clear what is the difference between profiles, modules, and libraries. Looks like they are used interchangeably.

Also, guestbook tutorial shows how to use `(kit/list-modules)` and `(kit/install-module)` to install one of the additional modules from /kit-clj/modules project.

But how to install additional modules that are located in `libs`? Application profiles documentation section mentions that it's possible to add a new library during the project creation time, but doesn't mention how to add it to an existing project.

A separate documentation section how to create a new module (library) using `integrant` may be also helpful, to deepen understanding of how it all works in kit.

**Comment by yogthos** [comment]
Thanks for the feedback. I definitely intend to add a section in documentation discussing how modules work.

Short answer is that modules are templates that inject functionality into user code within the project. A module can add libraries, but a module can't exist in a library. Meanwhile, profiles work similarly to modules, expect that they're executed at project creation time.

**Comment by yogthos** [comment]
Technically, everything profiles do could be achieved using modules, and I would be open to consolidating the two ideas going forward. Profiles are largely just there for convenience, and the flags could simply trigger appropriate modules when specified.

And you're correct regarding the modules repo. The idea is that modules are simply a standalone git repository, and anybody can make their own. The official modules will be packaged in the official repo, but they don't have any privileged status. And just added some docs on how the modules work, hopefully will help clear up a few things :)  https://kit-clj.github.io/docs/modules.html

@nikolap you might have some thoughts on this as well

**Comment by jwhitlark** [comment]
The current documentation makes clear the difference between profiles and modules.  While I like the idea of a single interface, it looks like that ship has sailed.  Should this be closed?
