### ISSUE TITLE
auto reload sql queries in dev mode

### ISSUE THREAD

**Issue by yogthos** [kit-clj/kit#128]
Currently, whenever hugsql queries are changed, the user has to run `(reset)` to load new queries. Proposed change would be to automatically reload queries when the app is running in dev mode so that `(reset)` isn't needed.

This issue relates to discussion regarding automatically [reloading routes in dev](https://github.com/kit-clj/kit/issues/48).

**Comment by gerdint** [comment]
I will have a go at this!

**Comment by gerdint** [comment]
I would still want to have a go at this but it is subject to my available time which appears scarce for the time being, so I wouldn't want to block anyone else who is so inclined!

**Comment by yogthos** [comment]
Oh yeah no worries, and absolutely no rush. I haven't really had much time myself either lately. :)

**Comment by vollcheck** [comment]
Hey, I've implemented mentioned functionality - at least for the `kit-sql-conman` library.

https://github.com/kit-clj/kit/pull/145

**Comment by gerdint** [comment]
@vollcheck Thanks for working on this!

**Comment by vollcheck** [comment]
@gerdint no problem ;)

@yogthos I believe that issue can be closed now as https://github.com/kit-clj/kit/pull/145 is merged alreaday.

**Comment by yogthos** [comment]
and I just pushed out the new version to clojars, thanks again for spearheading this :)
