### ISSUE TITLE
Remove Alpha warning from the README

### ISSUE THREAD

**Issue by markokocic** [kit-clj/kit#134]
kit framework is there for a while. It has been pretty stable and is production ready.

It may be time to remove alpha warning from the README, since it gives a wrong impression it's something not to be used in production. This can slow down the acceptance.

If a disclaimer about some components is still needed, move it to the docs section for that component.

**Comment by yogthos** [comment]
Agreed, I think it's safe to say the module system is unlikely to have major user facing changes at this point.
