### ISSUE TITLE
Default REPL_HOST is open to the wide internet

### ISSUE THREAD

**Issue by N-litened** [kit-clj/kit#21]
Hi all!
I am playing with tutorial's guestbook example, the framework looks really promising to me as a beginner.

Though, If I understand correctly (see screenshot from generated system.edn) that default REPL host is 0.0.0.0 even for `:prod` profile? Shouldn't the default for `:prod` be something like 127.0.0.1, otherwise it's open for everyone to connect? My opsec knowledge is rudimentary, but I can imagine accidentally making an environment variable with a typo REPL_HSOT=127.0.0.1, and by default exposing a production system's security instead of just making remote REPL unusable.

<img width="277" alt="Screen Shot 2022-01-21 at 22 22 21" src="https://user-images.githubusercontent.com/1075301/150590306-febd6abf-fa23-4d17-8c59-1d63445d9ee7.png">

As a fellow clojurist **rcaze** noticed, usually a "real" production system should also have a firewall, but an extra fool-proof layer of security is always nice.

**Comment by yogthos** [comment]
Agreed, it would safer to listen on localhost as the default.

**Comment by markokocic** [comment]
You are right. On the other side, I’m not sure repl module should be enabled in default profile. If someone needs it in production it can be added as a module. During development we have nrepl aliases which should cover basic repl needs.

**Comment by yogthos** [comment]
I'd be ok moving socket repl to a module if @nikolap has no objections :)

**Comment by nikolap** [comment]
Makes sense for both:

- Changing the default host it to `"127.0.0.1"`
- Removing the nrepl from the default profile. We can also kill the "+bare" template profile if this is the case

Just realized in terms of sane defaults, we should generate a random 16-char cookie secret on template generation instead of a fixed one. That way even those people who don't configure an env var with a cookie secret don't have the same one.

**Comment by nikolap** [comment]
Released a new build of the template resolving 

- Changing the default host it to "127.0.0.1"
- Removing the nrepl from the default profile. We can also kill the "+bare" template profile if this is the case
