### ISSUE TITLE
Correct way of including complied app.js in HTML

### ISSUE THREAD

**Issue by arca0** [kit-clj/kit#31]
It seems like the [documentation](https://kit-clj.github.io/docs/clojurescript.html) is missing clear information on how to actually include your compiled JS in your application to start using reagent/cljs. 

That is, there is information on the content of shadow-cljs.edn, and its content, specifically `:output-dir` and `:asset-path`, but it's not really clear what is the canonical way of adding the produced JS file to your HTML. In Luminus, the compiled JS file would be available in `/js/app.js`. In Kit, that does not seem to work. `target/classes/cljsbuild/public/js` is not included in `:resources` (should it be?).

As a result, the instruction to call `(js/alert "Hi")` from the REPL does not succeed, since there is no real JS runtime available.

**Comment by yogthos** [comment]
Yeah that's a good catch. The module wires this up, but needs to be documented as well.

**Comment by arca0** [comment]
Ah, I see now that it's adding code in home.html, that makes sense. I got it working in a fresh project, so there's probably something missing in the project I've been working on. I'll look into it and perhaps update the docs.

**Comment by arca0** [comment]
Addressed in https://github.com/kit-clj/kit-clj.github.io/pull/16

**Comment by arca0** [comment]
I think this is good for now, closing this issue.
