### ISSUE TITLE
the init! function is never invoked in core.cljs when using the cljs template

### ISSUE THREAD

**Issue by luciodale** [kit-clj/kit#33]
`mount-root` is properly invoked after editing and saving the file. However, when the `js/app.js` bundle is first served, the `init!` function is completely ignored.

To reproduce:

```clojure
(defn ^:export ^:dev/once init! []
  (prn "init in here")
  (mount-root))
```

You can see that the string never shows up in the console.

**Comment by luciodale** [comment]
Adding `:init-fn` to the `shadow-cljs` config fixed it.

```clojure
:modules    {:app {:entries [exporter.app.core]
                               :init-fn exporter.app.core/init!}}
```

Should I create a PR?

**Comment by nikolap** [comment]
> Should I create a PR?

If you could that would be great! Thanks for looking into this

**Comment by yogthos** [comment]
I've updated the module config [here](https://github.com/kit-clj/modules/blob/master/cljs/assets/shadow-cljs.edn)
