### ISSUE TITLE
Released app doesn't serve shadow-cljs generated script

### ISSUE THREAD

**Issue by luciodale** [kit-clj/kit#34]
Specifically, the `build.clj` generated file should first invoke the `(build-cljs nil)` function, and then the `(b/uber ...)` one like in the following example:

```clojure
(defn uber [_]
  (b/compile-clj {:basis basis
                  :src-dirs ["src/clj" "env/prod/clj"]
                  :class-dir class-dir})
  (build-cljs nil) ;; <----- Before building jar to be picked up and packaged along with the other assets
  (println "Making uberjar...")
  (b/uber {:class-dir class-dir
           :uber-file uber-file
           :main main-cls
           :basis basis}))
```

Currently, the script generated by shadow-cljs returns 404, as it's not included in the already generated jar, happening one step ahead.

**Comment by yogthos** [comment]
`build-cljs` shouldn't be taking any arguments by default:

```clojure
 (defn build-cljs [] 
   (println "npx shadow-cljs release app...") 
   (let [{:keys [exit]
          :as   s} 
         (sh "npx" "shadow-cljs" "release" "app")]
     (when-not (zero? exit)
       (throw (ex-info "could not compile cljs" s)))))
```

it looks like the issue was caused by a [typo](https://github.com/kit-clj/modules/commit/c33a8823097b07cab2613e66d7de1144829173d9) in `shadow-cljs.edn`. If you pull new modules the issue should be resolved. I'm seeing the `app.js` file in the uberjar right now.

**Comment by luciodale** [comment]
I see. I think I don’t have that typo in my project, but I will pull the new module and let you know in a bit

**Comment by luciodale** [comment]
After starting a fresh project and adding the cljs module the problem seems to persist, that is the `/js/app.js` file is not found

**Comment by yogthos** [comment]
Ah ok, I think I know what the issue is. Running through the steps below I see that the `app.js` is generated in `cljsbuild/public/js/app.js` which is what's specified in `shadow-cljs.edn`

```
$ npm install
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 98 packages, and audited 99 packages in 6s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 8.4.1 -> 8.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.5.0
npm notice Run npm install -g npm@8.5.0 to update!
npm notice

$ make uberjar
clj -T:build all
Downloading: luminus/ring-ttl-session/0.3.3/ring-ttl-session-0.3.3.pom from clojars
Downloading: expiring-map/expiring-map/0.1.9/expiring-map-0.1.9.pom from clojars
Downloading: net/jodah/expiringmap/0.5.9/expiringmap-0.5.9.pom from central
Downloading: expound/expound/0.8.9/expound-0.8.9.pom from clojars
Downloading: net/jodah/expiringmap/0.5.9/expiringmap-0.5.9.jar from central
Downloading: luminus/ring-ttl-session/0.3.3/ring-ttl-session-0.3.3.jar from clojars
Downloading: expiring-map/expiring-map/0.1.9/expiring-map-0.1.9.jar from clojars
Downloading: expound/expound/0.8.9/expound-0.8.9.jar from clojars
Cleaning target
Writing Pom...
Compiling Clojure...
npx shadow-cljs release app...
Making uberjar...

$ jar tf target/guestbook-standalone.jar  | grep app.js
cljsbuild/public/js/app.js
```

I've switched the path `https://github.com/kit-clj/modules/blob/master/cljs/assets/shadow-cljs.edn#L8` in the `shadow-cljs.edn` config, and I'm seeing the `app.js` artifact in the expected place now with the app loading it as expected from the jar.

Let me know if the fix works on your end.

**Comment by luciodale** [comment]
Yup it fixes it thanks for taking a look :)

**Comment by luciodale** [comment]
I believe that deps.edn now needs in the paths: `"target/classes"` vs `"target/classes/cljsbuild"`

**Comment by yogthos** [comment]
Oh yeah good catch, just fixed that

**Comment by yogthos** [comment]
Actually, I just realized that `target/classes` isn't necessary. However, it would be useful to have `src/cljs` there instead.

**Comment by yogthos** [comment]
Oh, I `target/classes` is still needed for dev mode

**Comment by yogthos** [comment]
ok should be all working now
