### ISSUE TITLE
incorrect cookie session config

### ISSUE THREAD

**Issue by jaimesangcap** [kit-clj/kit#40]
Seems like the generated `system.edn` for `:handler/ring` does not match the expected key and shape in `<project>.web.middleware.core`

`system.edn` notice key `:cookie-session-config`
```
:handler/ring
 {:router                #ig/ref :router/core
  :api-path              "/api"
  :cookie-session-config {:cookie-secret          #or [#env COOKIE_SECRET "XLHSGXBMTTBTRCHU"]
                          :cookie-name            "io.klei.lms"
                          :cookie-default-max-age 86400}
```

 In `<project>.web.middleware.core`
The `(cookie/cookie-store cookie-session)` expects the `{:key "SECRET"}` for the secrey key instead of `:cookie-secret` and data type as bytes instead of string?

```

(defn wrap-base
  [{:keys [metrics site-defaults-config cookie-session] :as opts}]
  (fn [handler]
    (cond-> ((:middleware env/defaults) handler opts)
            true (defaults/wrap-defaults
                   (assoc-in site-defaults-config [:session :store] (cookie/cookie-store cookie-session))))))
```

Happy to create a PR. If this is an actual issue. Seems it is a change in the lein-template?

**Comment by nikolap** [comment]
Good find, thanks for the report! That's indeed an issue. Should actually make sure the cookie-session-config keys are being used as well, i.e. the cookie name and default max age since that usually is passed to the session config.

If you have the time and interest a PR would be amazing. Otherwise I can take a look sometime later in the week

**Comment by nikolap** [comment]
@jaimesangcap let me know if the new build fixes the issue for you! Thanks again for the report

**Comment by jaimesangcap** [comment]
Beat me to it. I will try it and report back for any issues. 
Thanks for the quick fix!
