### ISSUE TITLE
Add a default configuration for xtdb

### ISSUE THREAD

**Issue by green-coder** [kit-clj/kit#44]
For the same reason as there is a default http port, it would be nice to have a default config for people to use out of the box.

I suggest to use `rockdb` as a default because it runs on both x86 (PC) and aarm64 (Mac M1) CPUs.

https://github.com/kit-clj/kit/blob/e81daa9b216101a9411dea635b539857923ca9c1/libs/lein-template/resources/leiningen/new/kit/resources/system.edn#L73-L75

**Comment by nikolap** [comment]
That's a good idea! Would you be interested in opening a PR for that?

**Comment by green-coder** [comment]
Yes, I am preparing one right now.
