### ISSUE TITLE
Calling `(reset)` doesn't work anymore: "start-app already refers to #'asdf.core/start-app in namespace: user"

### ISSUE THREAD

**Issue by elmehalawi** [kit-clj/kit#63]
This just started happening. I can no longer call `(reset)` in the REPL. I get the following error:

> start-app already refers to: #'asdf.core/start-app in namespace: user

I haven't changed the contents of user.clj in a while so I'm unsure what could be causing this.

**Comment by elmehalawi** [comment]
Still don't know what that was about, but it seems restarting fixed that.

**Comment by yogthos** [comment]
Looks like you ended up with a stale state in the repl somehow.
