### ISSUE TITLE
Re-Frame example

### ISSUE THREAD

**Issue by andrzejsliwa** [kit-clj/kit#67]
May I ask you to point me to real example using kit and re-frame (maybe with sente). Also example with Fulcro would be great. You know to provide full examples with SPA on top of Kit.

Thx!

**Comment by markokocic** [comment]
There is a support for sente in the sente module, you can look at the documentation [here](https://kit-clj.github.io/docs/clojurescript.html#websockets).

**Comment by martinklepsch** [comment]
I think this can be closed maybe?
