### ISSUE TITLE
Route paths don't work properly without final "/" - address bar is blank, web page not responsive

### ISSUE THREAD

**Issue by ieugen** [kit-clj/kit#69]
Hi,

I can't access routes mounted to "/example-route" . 
It turns address bar blank and page does not work in Firefox. 
I must use "/example-route/" . 

I believe this is because routes, by default only listen to "/" and not to "" as well. 
This might be a non issue for more seasoned devs, but to me it is. 

How I got here:
I have a new porject started with html and htmx modules.
I got an error because both are trying to use the same route "/" so I decided to move htmx to "/htmx-clicked" .
I changed the entry to:
```clojure
:reitit.routes/ui {:base-path "/htmx-clicked",
                    :env #ig/ref :system/env}
```

Opened `http://localhost:3000/htmx-clicked` and the address bar went blank and web page is not responding. 
I can't even right click inside of it in FF.

**Comment by ieugen** [comment]
I managed to fix this by rendering the same route at both "" and "/" . 

Should the examples be updated? 
Should we mount the htmx example by default to anther route ?!

```clojure
(defn ui-routes [_opts]
  [["" {:get home}]
   ["/" {:get home}]
   ["/clicked" {:post clicked}]])
```

**Comment by yogthos** [comment]
I think the proper way would be to do

```clojure
(defn ui-routes [_opts]
  [""
   ["/" {:get home}]
   ["/clicked" {:post clicked}]])
```

**Comment by ieugen** [comment]
Thanks, should I update the examples (modules)?

**Comment by yogthos** [comment]
Yeah, that'd be a good idea if you have time. :)

**Comment by ieugen** [comment]
Well, your solution does not seem to work. 
I get the same behavior as in normal case.

**Comment by yogthos** [comment]
Oh sorry, misread the original question. Here's what the official docs for Reitit suggest here https://github.com/metosin/reitit/blob/master/doc/ring/slash_handler.md

**Comment by ieugen** [comment]
The answer is in the docs you sent. 
To have good errors, they recommend composing it with default handler:

handler.clj
```clojure
(ring/routes
      ;; Handle trailing slahs in routes
      ;; https://github.com/metosin/reitit/blob/master/doc/ring/slash_handler.md
      (ring/redirect-trailing-slash-handler)
      (ring/create-default-handler
       {:not-found
        (constantly {:status 404, :body "Page not found"})
        :method-not-allowed
        (constantly {:status 405, :body "Not allowed"})
        :not-acceptable
        (constantly {:status 406, :body "Not acceptable"})}))
```
