### ISSUE TITLE
Installation failed, could not locate the artifact for template

### ISSUE THREAD

**Issue by hjbolide** [kit-clj/kit#74]
Hi,

Tried to install Kit following command:

`clojure -Ttools install com.github.seancorfield/clj-new '{:git/tag "v1.2.381"}' :as new`

and

`clojure -Tnew create :template io.github.kit-clj :name self/kit`

Second command failed due to the following error:

> Downloading: com/hypirion/io/0.3.1/io-0.3.1.jar from clojars
> Downloading: pedantic/pedantic/0.2.0/pedantic-0.2.0.jar from clojars
> 
> Failed with (underlying error, possibly from Maven):
>     Could not find artifact io.github.kit-clj:deps-template:jar:0.1.28 in central (https://repo1.maven.org/maven2/)
> 
> Execution error (ExceptionInfo) at clj-new.helpers/resolve-remote-template (helpers.clj:176).
> Could not locate the artifact for template: io.github.kit-clj
> 	Tried coordinates:
> 		{io.github.kit-clj/clj-template #:mvn{:version "RELEASE"}}
> 		[io.github.kit-clj/boot-template "RELEASE"]
> 		[io.github.kit-clj/lein-template "RELEASE"]

Any idea when the template would be re-instated in maven repo? or it has been moved permanently somewhere else?

**Comment by yogthos** [comment]
Hmm, I can't reproduce this locally on my machine. Might be worth cleaning maven cache in your `~/.m2/` folder.

**Comment by hjbolide** [comment]
Blew away everything under ~/.m2, reinstalled clojure, re-ran those command, got stuck at the same place.
Also in this url: https://repo1.maven.org/maven2/io/github/, can't seem to find kit-clj at all?

**Comment by yogthos** [comment]
Ah ok, I tried blowing m2 away locally and can reproduce this now as well.

**Comment by yogthos** [comment]
@rads might be related to [this](https://github.com/kit-clj/kit/pull/65)?

**Comment by yogthos** [comment]
@hjbolide and should be back to working here, you may have to blow `.m2/repository/io/github/kit-clj` away again, but should work otherwise

**Comment by hjbolide** [comment]
Yep confirmed it's working now, thanks a lot @yogthos.

**Comment by hjbolide** [comment]
Closing the issue as it has been fixed.

**Comment by yogthos** [comment]
Thanks for the report, glad we got it sorted!
