### ISSUE TITLE
Expose query-fn for production use

### ISSUE THREAD

**Issue by crimsonhawk47** [kit-clj/kit#79]
It looks like the only way to access `query-fn` is to access `integrant.repl.state`. This is a dev dependency, and this means HugSQL can't be used in production. 

I'm not sure if that was the intention. In Luminus, I used HugSQL queries in production. Maybe we should expose this function.

**Comment by yogthos** [comment]
That's not correct. You will have a `system` in production and it will contain all the components that are specified in `system.edn`. This system is defined in the core namespace as seen [here](https://github.com/kit-clj/demo-guestbook/blob/master/src/clj/londonclj/guestbook/core.clj#L27).

**Comment by crimsonhawk47** [comment]
> That's not correct. You will have a `system` in production and it will contain all the components that are specified in `system.edn`. This system is defined in the core namespace as seen [here](https://github.com/kit-clj/demo-guestbook/blob/master/src/clj/londonclj/guestbook/core.clj#L27).

What would be a recommended approach for writing code that accesses system and will work in both dev and prod? In test_utils, there is `(or @core/system state/system)`. Should I use that to access the `query-fn` where needed? 

Or is this not the intended way to access components? Should I be passing down a subset of system from component to component?

**Comment by yogthos** [comment]
You shouldn't be accessing the system directly in your code. The proper way is to do the wiring of components in `system.edn`. For example, you can see the `:reitit.routes/api` component referencing `:query-fn` [here](https://github.com/kit-clj/demo-guestbook/blob/master/resources/system.edn#L37). The queries will then be available within the scope of that component.

In general, the code should be structured so that any resources that are being referenced are passed around explicitly. Ideally, you want to keep any IO operations close to the edges, and avoid passing resources like query functions deep into the call stack.

I recommend spending a bit of time looking over how the guestbook project is set up.

**Comment by crimsonhawk47** [comment]
I'm actually working in the guestbook project. I didn't notice `query-fn` was getting passed to `:reitit.routes/api` because it's not explicitly used in any example. 

> In general, the code should be structured so that any resources that are being referenced are passed around explicitly. Ideally, you want to keep any IO operations close to the edges, and avoid passing resources like query functions deep into the call stack.

This has been my understanding too. In the case of using `query-fn` in an api-route, I would pass `query-fn` to a route like `/login`, but I would only use it in that top level function and pass the resulting data to whatever needs it. Does that sound right?

**Comment by yogthos** [comment]
Yup, that sounds correct to me.

**Comment by Bost** [comment]
I think I managed to get the same or very similar problem too. `clj -Sforce -T:build all` was complaining about `Could not locate integrant/repl/state ... on classpath`. I solved it with https://github.com/FdK-Stuttgart/Associations/commit/ce506de57493d6e5009f580431f73f962dbff92e

**Comment by nikolap** [comment]
Makes sense. integrant.repl namespace is provided by https://github.com/weavejester/integrant-repl which is only a dependency (by default*) in the [dev alias](https://github.com/kit-clj/kit/blob/master/libs/deps-template/resources/io/github/kit_clj/kit/deps.edn#L47) for use in development.

Personally I tend to use the pattern you linked in your comment. There's also [this approach](https://github.com/nikolap/FrameworkBenchmarks/blob/add-clojure-kit/frameworks/Clojure/kit/src/clj/io/github/kit_clj/te_bench/web/routes/bench.clj#L13) if you want to avoid passing along system component dependencies in route data. It instead passes it in as an arg to your routes. This is more performant, but either would be a correct practice.

Note *: You can include this as a dependency in your project overall, but I would recommend against it as it's meant for use in development, not production.
