### ISSUE TITLE
Support nrepl in projects

### ISSUE THREAD

**Issue by markokocic** [kit-clj/kit#9]
It would be nice if the default kit project template would include `nrepl` server support in addition to server repl.

**Comment by nikolap** [comment]
Thanks! Released a simple library for [nrepl support](https://clojars.org/io.github.kit-clj/kit-nrepl) and added it to the clj-new template with the `+nrepl` profile. If you want to enhance it further feel free to throw up a PR

**Comment by markokocic** [comment]
hi @nikolap 

I see a few problems with `nrepl`.

1. it's either `repl` or `nrepl`, why not both in the same time by default, on different ports?
2. `nrepl` doesn't start automatically after starting the application with `clj -M:dev`
3. running `(reset)` while being connected to the nrepl the connection gets dropped and nrepl client disconnects.

In my opinion, both `repl` and `nrepl` should be treated like part of the infrastructure, not like part of the application. They should be started wit the application dev profile and never stopped until user exits. `(go)`, `(halt)` and `(reset)` should not affect repls, only application. In principle something like the old luminus behaviour regarding repls.

Not sure how this could be achieved using `integrant` components. Maybe having two systems `kit` and `app` where `kit` is stated by default during startup and `app` being a base component for all other application related components and modules. Or to hardcode repl startup on application start without making it an integrant component.

What do you and @yogthos think?

**Comment by nikolap** [comment]
Ah, maybe I misunderstood what you wanted it for. 

Right now the libraries that provide the socket REPL and nREPL support are meant to be used to access a running system separate from your machine. I figured these are mutually exclusive, but I guess you could have both running on a staging or production environment?

I think what you're looking for is to add it to the development environment... and yes it shouldn't be a problem to add nREPL that to the `user.clj` namespace in the clj-new template. I should have some time next week to poke at this, but also happy to welcome a PR.

**Comment by markokocic** [comment]
Hi @nikolap, yes I was thinking more of the development environment.

In ideal case, starting `clj -M:dev` should be an equivalent of the `lein repl`, e.g., starting fully setup dev profile and nrepl server automatically.

lein repl source is [here](https://github.com/technomancy/leiningen/blob/master/src/leiningen/repl.clj), though it contains quite a bit of the `lein` specific stuff.

A minimal version would just start nrepl on a random port upon startup and leave it connected as long as it's running. I'll try to wrap my head around the codebase and come up with the pull request during the week.

If lib-repl and lib-nrepl are meant to be used in prod, none of them should be enabled by default since default app is pretty minimal, and they can be converted to modules to be added later if needed.

**Comment by nikolap** [comment]
I see what you mean. Makes sense. We can include the nrepl by default in the dev profile in the template. I think [nrepl.cmdline](https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/cmdline.clj) is probably what we need? Not 100% sure as I just use the IntelliJ nREPL with the project classpath

Re the libraries, it would certainly simplify to remove it from the default template, then we can also drop the `+bare` profile.

Any thoughts @yogthos ?

**Comment by yogthos** [comment]
Yeah, I think it'd be fine to include nREPL by default. And yeah, we'd need something similar to what cmdline does to make sure right source paths are included.

**Comment by gdrte** [comment]
I thought the same and I have modified dev profile to add these extra deps and replaced pjstadig.humane-test-output with nrepl.cmdlin.
:extra-deps  {
                                nrepl/nrepl                     {:mvn/version "0.9.0-beta3"}
                                refactor-nrepl/refactor-nrepl   {:mvn/version "3.0.0-alpha13"}
                                cider/cider-nrepl               {:mvn/version "0.27.2"}}
 
                   :main-opts ["-m" "nrepl.cmdline" "--middleware" "[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"]}
