### ISSUE TITLE
update the docs to use integrant system as a parameter instead of via routes

### ISSUE THREAD

**Issue by yogthos** [kit-clj/kit#90]

**Comment by vollcheck** [comment]
Hey, happy to help here but the title sounds vaguely :) can you elaborate more?

**Comment by yogthos** [comment]
Oh I think this might be done already, but might be worth checking. Basically, original template setup would pull components out of route data. However, these are already available, so the new approach is to just pass `opts` directly to `api-routes` and access them from there as seen here https://github.com/kit-clj/kit/blob/master/libs/deps-template/resources/io/github/kit_clj/kit/src/clj/web/routes/api.clj

The issue was to make sure all the docs were updated to illustrate the new approach.

**Comment by vollcheck** [comment]
Hey, I've reviewed whole documentation and I found only one place in the [kit-hato](https://kit-clj.github.io/docs/kit-hato.html) library documentation where the code is obsolete.

I put it as a part of general documentation overhaul [here](https://github.com/kit-clj/kit-clj.github.io/pull/67).

**Comment by vollcheck** [comment]
> on a random note, would you like me to add you as a maintainer? :)

 Yes, I'm happy to be a part of this project!

**Comment by yogthos** [comment]
Awesome, sent an invite!
